### ISSUE TITLE
在构建项目是出现以下错误，好像是go的依赖无法下载

### ISSUE THREAD

**Issue by dsbzbc121233** [passerma/docker-pull#2]
D:\wwwroot\docker-pull-master>go build -o docker-pull
go: downloading github.com/gin-gonic/gin v1.9.1
go: downloading github.com/robfig/cron v1.2.0
go: downloading github.com/typa01/go-utils v0.0.0-20181126045345-a86b05b01c1e
go: downloading github.com/xiao-ren-wu/restgo v1.0.2
go: downloading gopkg.in/yaml.v2 v2.4.0
src\util\docker.go:12:2: github.com/xiao-ren-wu/restgo@v1.0.2: Get "https://proxy.golang.org/github.com/xiao-ren-wu/restgo/@v/v1.0.2.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
src\util\conf.go:8:2: gopkg.in/yaml.v2@v2.4.0: Get "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
src\controller\route.go:10:2: github.com/gin-gonic/gin@v1.9.1: Get "https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.9.1.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
src\controller\route.go:8:2: github.com/robfig/cron@v1.2.0: Get "https://proxy.golang.org/github.com/robfig/cron/@v/v1.2.0.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
src\controller\route.go:11:2: github.com/typa01/go-utils@v0.0.0-20181126045345-a86b05b01c1e: Get "https://proxy.golang.org/github.com/typa01/go-utils/@v/v0.0.0-20181126045345-a86b05b01c1e.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by passerma** [comment]
go 镜像设置了吗

**Comment by passerma** [comment]
> D:\wwwroot\docker-pull-master>go build -o docker-pull go: downloading github.com/gin-gonic/gin v1.9.1 go: downloading github.com/robfig/cron v1.2.0 go: downloading github.com/typa01/go-utils v0.0.0-20181126045345-a86b05b01c1e go: downloading github.com/xiao-ren-wu/restgo v1.0.2 go: downloading gopkg.in/yaml.v2 v2.4.0 src\util\docker.go:12:2: github.com/xiao-ren-wu/restgo@v1.0.2: Get "https://proxy.golang.org/github.com/xiao-ren-wu/restgo/@v/v1.0.2.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. src\util\conf.go:8:2: gopkg.in/yaml.v2@v2.4.0: Get "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. src\controller\route.go:10:2: github.com/gin-gonic/gin@v1.9.1: Get "https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.9.1.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. src\controller\route.go:8:2: github.com/robfig/cron@v1.2.0: Get "https://proxy.golang.org/github.com/robfig/cron/@v/v1.2.0.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. src\controller\route.go:11:2: github.com/typa01/[go-utils@v0.0.0-20181126045345-a86b05b01c1e](mailto:go-utils@v0.0.0-20181126045345-a86b05b01c1e): Get "https://proxy.golang.org/github.com/typa01/go-utils/@v/v0.0.0-20181126045345-a86b05b01c1e.zip": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

go 镜像设置了吗

**Comment by dsbzbc121233** [comment]
> > D：\wwwroot\docker-pull-master>go build -o docker-pull go：下载 github.com/gin-gonic/gin v1.9.1 go：下载 github.com/robfig/cron v1.2.0 go：下载 github.com/typa01/go-utils v0.0.0-20181126045345-a86b05b01c1e go：下载 github.com/xiao-ren-wu/restgo v1.0.2 go：下载 gopkg.in/yaml.v2 v2.4.0 src\util\docker.go：12：2：github.com/xiao-ren-wu/restgo@v1.0.2：获取“https://proxy.golang.org/github.com/xiao-ren-wu/restgo/@v/v1.0.2.zip“： dial tcp 142.251.43.17：443： connectex： 连接尝试失败，因为连接方在一段时间后未正确响应，或者建立的连接失败，因为连接的主机无法响应。src\util\conf.go：8：2：gopkg.in/yaml.v2@v2.4.0：获取“https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip”：拨号 tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或者建立连接失败，因为连接的主机无法响应。src\controller\route.go：10：2：github.com/gin-gonic/gin@v1.9.1：获取“https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.9.1.zip”：拨号 tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或者建立连接失败，因为连接的主机无法响应。src\controller\route.go：8：2：github.com/robfig/cron@v1.2.0：获取“https://proxy.golang.org/github.com/robfig/cron/@v/v1.2.0.zip”：拨号 tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或已建立连接失败，因为连接的主机无法响应。src\controller\route.go：11：2：github.com/typa01/ [go-utils@v0.0.0-20181126045345-a86b05b01c1e](mailto:go-utils@v0.0.0-20181126045345-a86b05b01c1e)：获取“https://proxy.golang.org/github.com/typa01/go-utils/@v/v0.0.0-20181126045345-a86b05b01c1e.zip”：拨号 tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或建立连接失败，因为连接的主机无法响应。
> 
> go 镜像设置了吗

好像没有设置，应该要怎么设置啊？谢谢

**Comment by passerma** [comment]
> > > D：\wwwroot\docker-pull-master>go build -o docker-pull go：下载 github.com/gin-gonic/gin v1.9.1 go：下载 github.com/robfig/cron v1.2.0 go：下载 github.com/typa01/go-utils v0.0.0-20181126045345-a86b05b01c1e go：下载 github.com/xiao-ren-wu/restgo v1.0.2 go：下载 gopkg.in/yaml.v2 v2.4.0 src\util\docker.go：12：2：github.com/xiao-ren-wu/restgo@v1.0.2：获取“[https://proxy.golang.org/github.com/xiao-ren-wu/restgo/@v/v1.0.2.zip“：](https://proxy.golang.org/github.com/xiao-ren-wu/restgo/@v/v1.0.2.zip%E2%80%9C%EF%BC%9A) dial tcp 142.251.43.17：443： connectex： 连接尝试失败，因为连接方在一段时间后未正确响应，或者建立的连接失败，因为连接的主机无法响应。src\util\conf.go：8：2：gopkg.in/yaml.v2@v2.4.0：获取“[https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip”：拨号](https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或者建立连接失败，因为连接的主机无法响应。src\controller\route.go：10：2：github.com/gin-gonic/gin@v1.9.1：获取“[https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.9.1.zip”：拨号](https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.9.1.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或者建立连接失败，因为连接的主机无法响应。src\controller\route.go：8：2：github.com/robfig/cron@v1.2.0：获取“[https://proxy.golang.org/github.com/robfig/cron/@v/v1.2.0.zip”：拨号](https://proxy.golang.org/github.com/robfig/cron/@v/v1.2.0.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或已建立连接失败，因为连接的主机无法响应。src\controller\route.go：11：2：github.com/typa01/ [go-utils@v0.0.0-20181126045345-a86b05b01c1e](mailto:go-utils@v0.0.0-20181126045345-a86b05b01c1e)：获取“[https://proxy.golang.org/github.com/typa01/go-utils/@v/v0.0.0-20181126045345-a86b05b01c1e.zip”：拨号](https://proxy.golang.org/github.com/typa01/go-utils/@v/v0.0.0-20181126045345-a86b05b01c1e.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或建立连接失败，因为连接的主机无法响应。
> > 
> > 
> > go 镜像设置了吗
> 
> 好像没有设置，应该要怎么设置啊？谢谢

``` sh
go env -w GOPROXY=https://goproxy.cn,direct
```

**Comment by dsbzbc121233** [comment]
> > > > D：\wwwroot\docker-pull-master>go build -o docker-pull go：下载 github.com/gin-gonic/gin v1.9.1 go：下载 github.com/robfig/cron v1.2.0 go：下载 github.com/typa01/go-utils v0.0.0-20181126045345-a86b05b01c1e go：下载 github.com/xiao-ren-wu/restgo v1.0.2 go：下载 gopkg.in/yaml.v2 v2.4.0 src\util\docker.go:12:2:github.com/xiao-任-wu/restgo@v1.0.2：获取“[https://proxy.golang.org/github.com/xiao-ren-wu/restgo/@v/v1.0.2.zip”：](https://proxy.golang.org/github.com/xiao-ren-wu/restgo/@v/v1.0.2.zip%E2%80%9C%EF%BC%9A)dial tcp 142.251.43.17：443： connectex： 连接尝试失败，因为连接方在一段时间后未正确响应，或者建立的连接失败，因为连接的主机无法响应。src\util\conf.go：8：2：gopkg.in/yaml.v2@v2.4.0：获取“[https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip”：拨号](https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或者建立连接失败，因为连接的主机无法响应。src\controller\route.go:10:2:github.com/gin-gonic/gin@v1.9.1：获取“[https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.9.1.zip”：拨号](https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.9.1.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或者建立连接失败，因为连接的主机无法响应。src\controller\route.go:8:2:github.com/robfig/cron@v1.2.0：获取“[https://proxy.golang.org/github.com/robfig/cron/@v/v1.2.0.zip”：拨号](https://proxy.golang.org/github.com/robfig/cron/@v/v1.2.0.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或已建立连接失败，因为连接的主机无法响应。src\controller\route.go:11:2:github.com/typa01/ [go-utils@v0.0.0-20181126045345-a86b05b01c1e](mailto:go-utils@v0.0.0-20181126045345-a86b05b01c1e)：获取“[https://proxy.golang.org/github.com/typa01/go-utils/@v/v0.0.0-20181126045345-a86b05b01c1e.zip”：拨号](https://proxy.golang.org/github.com/typa01/go-utils/@v/v0.0.0-20181126045345-a86b05b01c1e.zip%E2%80%9D%EF%BC%9A%E6%8B%A8%E5%8F%B7) tcp 142.251.43.17：443：connectex：连接尝试失败，因为连接方在一段时间后未正确响应，或建立连接失败，因为连接的主机无法响应。
> > > 
> > > 
> > > go 镜像设置了吗
> > 
> > 
> > 好像没有设置，应该要怎么设置啊？谢谢
> 
> ```shell
> go env -w GOPROXY=https://goproxy.cn,direct
> ```

感谢，已经编译成功了，但是在拉取镜像时显示参数错误。app.yml已经配置了，还有哪些文件需要配置吗？

**Comment by passerma** [comment]
拉取命令输入错了吧

**Comment by dsbzbc121233** [comment]
> 拉取命令输入错了吧

的确，这个只能使用阿里云的源吗？可以使用其他的dockers源码？

**Comment by passerma** [comment]
只支持阿里云
