### ISSUE TITLE
出现了一些问题

### ISSUE THREAD

**Issue by dsbzbc121233** [passerma/docker-pull#3]
![2VF% 4G1T_CC%F3EENW4%_1](https://github.com/passerma/docker-pull/assets/122132982/ef44568e-1ebd-4bdb-a3c8-60df26f3739a)
![T~M6F5ZK`F269I28JQHOR)0](https://github.com/passerma/docker-pull/assets/122132982/98268660-8738-4732-aa6c-193e3de37d77)
下载的文件是正常的，但是打包成tar文件之后就只有8kb了，有的文件没有被拷进去

**Comment by passerma** [comment]
压缩使用了 tar 命令，Windows 不支持
```go
cmd := exec.Command("tar", "-cf", tarName, "-C", dir+"/", ".")
```
